{{- if .Values.ingress.enabled -}}
{{- $fullName := include "aspnet-core-dotnet-core.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "aspnet-core-dotnet-core.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - host: {{ .Values.ingress.host }}.{{ .Values.ingress.fqdn }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: {{ include "aspnet-core-dotnet-core.fullname" . }}
            port: 
              number: 80
  {{- end }}
